# Generated by Django 5.2.13 on 2026-04-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'db_table': 'Category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название района')),
                ('description', models.TextField(blank=True, null=True)),
                ('additional', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название подкатегории')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Subcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubcategoryWord',
            fields=[
                ('pk', models.CompositePrimaryKey('subcategory', 'word', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Subcategory_Word',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст примера')),
                ('year', models.CharField(blank=True, max_length=20, null=True, verbose_name='Год')),
                ('multimedia', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Text',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TextWord',
            fields=[
                ('pk', models.CompositePrimaryKey('text', 'word', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Text_Word',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, verbose_name='Слово')),
                ('meaning', models.TextField(blank=True, null=True, verbose_name='Значение')),
                ('root', models.CharField(blank=True, max_length=255, null=True, verbose_name='Корень')),
                ('part_of_speech', models.CharField(blank=True, max_length=100, null=True, verbose_name='Часть речи')),
                ('grammatical_features', models.CharField(blank=True, max_length=255, null=True, verbose_name='Грамматические характеристики')),
                ('accent', models.CharField(blank=True, max_length=255, null=True, verbose_name='Слово с ударением')),
                ('multimedia', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Word',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WordHomonyms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Word_homonyms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WordSynonyms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Word_synonyms',
                'managed': False,
            },
        ),
    ]
